config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
    registrations: 'users/registrations'
  }
  resources :lists do
      resources :items
  end

  root "home#index"

  
end

app/models/list.rb
class List < ApplicationRecord
   belongs_to :user
    validates :title, presence: true
    after_create_commit {broadcast_prepend_to "lists"}
    after_update_commit {broadcast_replace_to "lists" }
    after_destroy_commit {broadcast_remove_to "lists"}

    has_many :items , dependent: :destroy

    def isEmpty
        if self.items.count < 1
          true
        else
          false
        end
      end


    
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /lists or /lists.json
  def index
    @lists = List.where(user_id:current_user.id)
    msg = ""
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit

  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    respond_to do |format|
      if @list.save
        format.turbo_stream do 
          # turbo_stream.prepend("lists", partial: "lists/list", locals: { list: @list })
         render turbo_stream:turbo_stream.prepend("flash_messages", partial: "layouts/show_flash_message", locals: { msg: "Item Created Successfully" })
        end
      else
        format.turbo_stream { render turbo_stream: turbo_stream.prepend(@list, partial:"lists/form",locals:{list:@list})}
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
  end
end
end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.turbo_stream do 
        render turbo_stream:turbo_stream.prepend("flash_messages", partial: "layouts/show_flash_message", locals: { msg: "Item Updated Successfully" })
        end
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@list, partial:"lists/list",locals:{list:@list})}
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy!

    respond_to do |format|
       render turbo_stream:turbo_stream.prepend("flash_messages", partial: "layouts/show_flash_message", locals: { msg: "Item Deleted" })
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_editform.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="d-flex  mt-3" style="gap:4px;">
  <div >
    <%= form.text_field :title , class:"form-control form-control-sm" , id:"form-textfield" %>
  </div>

  <div>
    <%= form.submit "update" , class:"btn btn-dark btn-sm" %>
  </div>
  <div>
  <%= link_to "cancel", list,class:"btn btn-dark btn-sm" %>
  </div>

</div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="d-flex flex-column align-items-center mt-3" style="width:100%; gap:4px;">
  <div >
    <%= form.text_field :title , class:"form-control form-control-sm" , id:"form-textfield" %>
  </div>

  <div>
   <%= button_tag "Create", type: "submit",  class:"btn btn-dark btn-sm" %>

  </div>
</div>
<% end %>

app/views/lists/_list.html.erb
<%= turbo_frame_tag dom_id(list) do%>
<li id="<%= dom_id(list) %>" class="list-group-item d-flex justify-content-between mt-1" style="background:#191654;color:white;border:none;">
  <span data-reflex="click->Counter#changeurl" data-id=<%= list.id %> data-controller="counter"><%= list.title %></span>
      <div>
      <%= link_to "Edit", edit_list_path(list) , class:"btn btn-primary btn-sm" ,style:"background:#24243e;border:none;"%>
      <button class="btn btn-primary btn-sm"  style="background:#24243e;border:none;" data-reflex="click->Counter#delete" data-id=<%= list.id%>>Delete</button>
      </div>
</li>

<% end %>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.prepend "lists", @list %>
<%= turbo_stream.update List.new, "" %>
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>
<%= turbo_frame_tag dom_id(@list) do%>
<%= render "editform", list: @list %>

<% end %>
<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<div style="width:100%;height:calc(100vh - 84px)" class="d-flex justify-content-center align-items-center">
<div class="card" style="width: 28rem; min-height:30rem;" id = "lists-card">
  <div class="card-header text-center">
    Todo App
  </div>
  <div class="card-body" >
    <h5 class="card-title display-6 text-center">Get Things Done!</h5>
    <%= render "lists/form" ,list:List.new %>

    <%= turbo_stream_from "lists"%>
    <ul class="list-group mt-2">
        <%= turbo_frame_tag "lists" do%>
  <% @lists.each do |list| %>
    <%= render list %>
  <% end %>
  <% end %>
</ul>
  </div>
</div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div style="width:100%;height:calc(100vh - 80px);" class="d-flex flex-column align-items-center justify-content-center">

<div class="card" style="width: 25rem;min-height:25rem;" id = "everything">
  <div class="card-header">
 <h5 class="card-title "><%= @list.title %></h5>
  </div>
    <div class="card-body">
          <ul class="list-group list-group-flush">
          <%= turbo_stream_from "items" %>
          <%= turbo_frame_tag "items" do %>    
  <% @list.items.each do |item| %>
<%= render "items/item" ,item:item %>
  <% end %>
  <% end %>
  </ul>
<%= turbo_frame_tag "additemstag" do %>
   <%= link_to 'Add Item', new_list_item_path(params[:id]),class:"btn btn-primary btn-sm mt-1" ,style:"background:#0f0c29;border:none;" %>
   <% end %>
  </div>
   <div class="card-footer text-body-secondary">
    <%= link_to "Edit", edit_list_path(@list) , class:"btn btn-primary btn-sm" ,style:"background:#24243e;border:none;"%>
    <%= link_to "Delete", @list ,method: :delete, class:"btn btn-primary btn-sm" ,style:"background:#24243e;border:none;" , data:{turbo:false}%>
  </div>
</div>


 <%= link_to "Back to lists", lists_path ,class:"btn btn-primary mt-4" ,style:"background:#24243e;border:none;" %>
</div>