config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
    registrations: 'users/registrations'
  }
  resources :lists do
      resources :items
  end

  root "home#index"

  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list


  validates :name, presence: true

  after_create_commit {broadcast_prepend_to "items"}
  after_update_commit {broadcast_replace_to "items" }
  after_destroy_commit {broadcast_remove_to "items"}


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET lists/1/items
  def index
    @items = @list.items
  end

  # GET lists/1/items/1
  def show
  end

  # GET lists/1/items/new
  def new
    @item = @list.items.build
  end

  # GET lists/1/items/1/edit
  def edit
  end

  # POST lists/1/items
  def create
    @item = @list.items.build(item_params)
    respond_to do |format|
    if @item.save
      # format.turbo_stream do
      #   render turbo_stream: turbo_stream.prepend("items", partial: "items/item", locals: { item: @item })
      #   flash.now[:notice] = "Item was successfully created."
      # end
      format.html { redirect_to "/lists/#{@item.list.id}", notice: "Item was successfully created." }
    else
      format.turbo_stream { render turbo_stream: turbo_stream.prepend(@list, partial:"items/form",locals:{list:@list})}
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @list.errors, status: :unprocessable_entity }
    end
  end
  end

  # PUT lists/1/items/1
  def update
    respond_to do |format|
    if @item.update(item_params)
      format.turbo_stream { flash.now[:notice] = "Item was successfully updated."}
    else
      format.turbo_stream { render turbo_stream: turbo_stream.prepend(@list, partial:"items/form",locals:{list:@list})}
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @list.errors, status: :unprocessable_entity }
    end
  end
  end

  # DELETE lists/1/items/1
  def destroy
    @item.destroy

    redirect_to list_items_url(@list)
    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Item was successfully removed."}
      format.html { redirect_to "/lists/#{@item.list.id}", notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_item
      @item = @list.items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:list_id, :name, :completed, :completed_at)
    end
end

app/views/items/_form.html.erb
<%= form_with(model: [@item.list, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-1">
    <%= f.text_field :name,placeholder: "Name" ,class:"form-control form-control-sm" ,id:"form-textfield"%>
  </div>
  <div class="field">
    <%= f.datetime_field :completed_at,class:"form-control form-control-sm mt-1" ,id:"form-textfield" %>
  </div>
    <div class="field">
    <%= f.check_box :completed ,class:"form-check-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-dark btn-sm mt-1" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= turbo_frame_tag dom_id(item) do%>
      <li class="list-group-item d-flex justify-content-between mt-1" id = <%= dom_id(item) %> style="background:#191654;color:white;border:none;">
      <small>Name: <%= item.name %></small>
      <small>completed: <%= item.completed %></small>
      <%= link_to 'Edit', edit_list_item_path(item.list, item),class:"btn btn-primary btn-sm" ,style:"background:#24243e;border:none;" %> 
      <button class="btn btn-primary btn-sm"  style="background:#24243e;border:none;" data-reflex="click->Counter#deleteItem" data-id=<%= item.id%>>Delete</button>

      </li>
      <% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>
<%= turbo_frame_tag dom_id(@item) do%>
<%= render 'form' %>
<%end %>
<%= link_to 'Show', [@item.list, @item] %> |
<%= link_to 'Back', list_items_path(@item.list) %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>List</th>
    <th>Name</th>
    <th>Completed</th>
    <th>Completed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.list %></td>
    <td><%= item.name %></td>
    <td><%= item.completed %></td>
    <td><%= item.completed_at %></td>
    <td><%= link_to 'Show', [item.list, item] %></td>
    <td><%= link_to 'Edit', edit_list_item_path(item.list, item) %></td>
    <td><%= link_to 'Destroy', [item.list, item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_list_item_path(params[:list_id]) %>

app/views/items/new.html.erb
<h1>New item</h1>
<%= turbo_frame_tag "additemstag" do%>
<%= render 'form' %>
<% end %>
<%= link_to 'Back', list_items_path(@item.list) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @item.list %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Completed:</b>
  <%= @item.completed %>
</p>

<p>
  <b>Completed at:</b>
  <%= @item.completed_at %>
</p>


<%= link_to 'Edit', edit_list_item_path(@item.list, @item) %> |
<%= link_to 'Back', list_items_path(@item.list) %>